Feat/page structure
codelittinc/next-base-project pull request #1
Opened 2023-08-16 14:26 UTC by kaiomagalhaes

2023-08-16 15:35 UTC, pvieiraguimaraes requested changes

2023-08-16 15:35 UTC, pvieiraguimaraes commented on src/app/accounts/[id]/page.tsx
> +export default function Home() {
@kaiomagalhaes it seems that this is an account page, I'd suggest having a different structure

```
accounts/
[id].tsx (this could be the user profile page)
new.tsx
styles.ts
```

we could even rename this function
```suggestion
export default function Account() {
```

2023-08-16 15:35 UTC, pvieiraguimaraes commented on src/app/page.tsx
> +export default function Home() {
I'd suggest moving the components folder to stay outside of the routes folder

2023-08-16 15:35 UTC, pvieiraguimaraes commented on src/app/page.tsx
> +    router.push(paths.accounts);
any reason to add it? I'd suggest removing this file.

2023-08-16 15:35 UTC, pvieiraguimaraes commented on src/app/store/slices/accountSlice.ts
> +import { StateCreator } from "zustand";
could we have the stores moved to src?

2023-08-16 15:35 UTC, pvieiraguimaraes commented on src/app/store/slices/accountSlice.ts
> +        accounts: currentState.accounts,
any reason to return all accounts here?

2023-08-16 15:47 UTC, kaiomagalhaes commented on src/app/accounts/[id]/styles.ts
> +const styles = {
That would only work if we are assuming these pages will always be equal and there would be no difference between them. Right now they are similar, but just because this is an example only.

2023-08-17 18:57 UTC, pvieiraguimaraes approved these changes

2023-08-17 18:57 UTC, merged